language: node_js
node_js:
  - 12.3.1
before_script:
  - npm install -g @angular/cli
cache:
  directories:
  - node_modules
install:
  - git checkout master
  - chmod +x ./travis/push.sh
script:
  - ng build --prod
after_success:
  - "./travis/push.sh"
env:
  global:
    secure: EFR9vtTIRecEwIhSfxghurIFnyayVhHt2JX4Z/q00lWw9uJomrz/H/k6vhCARNb1gsn4dqUKZlEEA0PdQysH+xCE9XnWZRUT0+E22q9YqhK2fQxkdKs9FG3qHbikuC2AeKLQNHVY9jFaaIDv5x0kewf8iPG0bbEcBz+KBuJMeCEFgcHjlMTLXJKeo3fDPpq56Mj2B5ZDmIi2xO1drlkfm00Jpedmn+dO3+Kd98pj0OOsXR4zrHrguZ/5cROB6nasaLXrfAANTtiib2S2tBMx7XbwrNr3bOlOn64mj9KYNKYW3g95CTaYVJGfX8eNwhaLhqxTgdZ8S6bUleG8yHpTMM8HmuJHhgP0JypNKc3u4N3cHVw9bE0fRcZ5tMD243VQvsxQ8QamVSaKq/AqdTdJho/v/RRcylzxE5ow6L3UYsRSn1zsbZSqllOgQF1Tu0hG3ZqnLrfpDwk4cV9iavvW5/9CbHlajN9TvhNnbpOqnGR0rls9y8eKRdmRMoMkGHqbpIPgdetrj1LbSMsjpycufqkTYs1myxwwIvEiIRx7cH1VmYlZHc3s9WSpI17sB/calrmL2rHlMQy+4FZ89HJPk8DnOSwY6zXgrmbrrzbws8E8Za93OHUYNfvGbUkgtmYjMGrnEmIPHzwSnFUhcmSVTd9fWWEKwoxUF1PCSC+jlSo=
