language: node_js
node_js:
- 12.3.1
before_script:
- npm install -g @angular/cli
- npm install
cache:
  directories:
  - node_modules
install:
- git checkout master
- chmod +x ./travis/push.sh
script:
- ng build --prod
notifications:
    email:
      recipients:
        - mike.anapa@gmail.com
      on_success: always
      on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  github_token: GH_TOKEN
  keep_history: true
  on:
    branch: build
