language: node_js
node_js:
- 12.3.1
branches:
  only:
  - master
addons:
  chrome: stable
before_script:
- npm install -g @angular/cli
cache:
  directories:
  - node_modules
install:
- git checkout master
- chmod +x ./travis/push.sh
script:
- ng build --prod
after_success:
- "./travis/push.sh"
env:
  global:
    secure: JZ2tm8NrXspNBzuXimw+QsN3f3sToQMnc0mp4DFZWVpUrxqKcBSFExjjM+znyDRsJgaKHtlAzhXY+fE2yo0smMLS60zdVE3vrD07X25qGXsfOA5WZcN22N9RQzMMXIVDnrfhR7wgOurhJvHaHa6gBMyjDvKQM8apTkIb3hJNPDVC7vAq2aRQ/zagGyDyAexSmDakY985PcuWShUIunzkVXf9fFnlOmL9QD56CoxYRLBB/DJ4bLbViSywOidQNEAguUUNBeOZ0qQq0TPRfyb05fCAjUtGUtYbUVq1PnxFEhcCCxUqOqGMYOPk5mi/IzdViTJj9+jEmHvfhzM0/ARV0jmYPIu15qveMLxXfxkuLAgcbGs2Tbs308UloZdZAG1a6sPHi2VKZtqRFExLiLeIh9KkxquhitFs/L/UG1o0R0G8wd+9f+6klVrPr81nhO2uyN/cgG+oNZtJaN0ADlx7AU7V6x2RB6r+yfl8h63mjGmOKsRX9SMh+WvjxW9we/0K9txMROAgW4km2QGMxd11NkJ+1Hps2kNROh/IDdujAi0uf5YObNQ9+fCRg1QjMsGkVr1phn0CosOv29pNwn7u9koi4PfmAnXYrbMMAC5+bur/qf5Cx2ZB3eAxTG0DI8OYB76eFJyWrDkF7DGz1ppFnKeaykTA7awh4mxrQsYsgsQ=
