language: node_js
node_js:
  - "lts/*"
before_install:
  - npm install -g @angular/cli
cache:
  directories:
    - ~/.npm
    - node_modules
    - ~/.cache
    override:
    - npm ci
    - npm run cy:verify
install:
  - npm ci
  - git checkout master
  - chmod +x ./travis/push.sh
script:
  - ng lint
  - ng build --prod
  - npm run cy:verify
  - npm run ci:cy-run
notifications:
    email:
      recipients:
        - mike.anapa@gmail.com
      on_success: always
      on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: www
  on:
    branch: master
